<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Auth\Module'                         => __DIR__ . '/Module.php',
  'Auth\Controller\LoginController'     => __DIR__ . '/src/Auth/Controller/LoginController.php',
  'Auth\Controller\LoginRestController' => __DIR__ . '/src/Auth/Controller/LoginRestController.php',
  'Auth\Factory\LoginControllerFactory' => __DIR__ . '/src/Auth/Factory/LoginControllerFactory.php',
  'Auth\Factory\UserServiceFactory'     => __DIR__ . '/src/Auth/Factory/UserServiceFactory.php',
  'Auth\Model\User'                     => __DIR__ . '/src/Auth/Model/User.php',
  'Auth\Service\UserService'            => __DIR__ . '/src/Auth/Service/UserService.php',
  'Auth\Service\UserServiceInterface'   => __DIR__ . '/src/Auth/Service/UserServiceInterface.php',
  'Auth\Entity\AuthStorage'             => __DIR__ . '/src/Entity/AuthStorage.php',
  'AuthTest\LoginControllerTest'        => __DIR__ . '/test/AuthTest/LoginControllerTest.php',
);
