<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'auth/login/login' => __DIR__ . '/view/auth/login/login.phtml',
    'error/404'        => __DIR__ . '/view/error/404.phtml',
    'error/index'      => __DIR__ . '/view/error/index.phtml',
);
