<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('OCTO') ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge') ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => '/img/octo-small-logo.png'))
        ->prependStylesheet('/css/404.css')
        ->prependStylesheet('/css/style.css')
        ->prependStylesheet('/css/bootstrap-theme.min.css')
        ->prependStylesheet('/css/bootstrap.min.css') ?>

</head>
<body>
<div class="container">
    <div class="greeting">
        <p>
            <?php if ($this->badRoute) : ?>
                The requested URL was not found on this server.
            <?php else : ?>
                Something went wrong. We will correct this soon, we promise! :)
            <?php endif; ?>
        </p>

        <img class="img-responsive" src="/img/404.png">

        <p>
            Meanwhile visit <a href="/">HOME</a> page.
        </p>
    </div>
    <div class="buffer"></div>
</div>
<!-- /container -->
<hr>
<footer>
    <div class="row">
        <div class="col-md-4 col-md-offset-4 text-center">
            <p>&copy; 2015 developed by Oleksii Volkov. All rights reserved.</p>
        </div>
    </div>
</footer>
</body>
</html>