<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Application\Module'                             => __DIR__ . '/Module.php',
  'Application\Controller\CommonController'        => __DIR__ . '/src/Application/Controller/CommonController.php',
  'Application\Controller\CommonRestfulController' => __DIR__ . '/src/Application/Controller/CommonRestfullController.php',
  'Application\Controller\IndexController'         => __DIR__ . '/src/Application/Controller/IndexController.php',
  'Application\Factory\FactoryUtil'                => __DIR__ . '/src/Application/Factory/FactoryUtil.php',
  'Application\Model\Model'                        => __DIR__ . '/src/Application/Model/Model.php',
  'Application\Service\CommonService'              => __DIR__ . '/src/Application/Service/CommonService.php',
  'Application\Service\CommonServiceInterface'     => __DIR__ . '/src/Application/Service/CommonServiceInterface.php',
  'Application\Service\Join'                       => __DIR__ . '/src/Application/Service/Join.php',
  'Application\Util\CachePath'                     => __DIR__ . '/src/Application/Util/CachePath.php',
  'Application\Util\StringUtils'                   => __DIR__ . '/src/Application/Util/StringUtils.php',
  'ApplicationTest\IndexControllerTest'            => __DIR__ . '/test/ApplicationTest/IndexControllerTest.php',
  'ApplicationTest\Bootstrap'                      => __DIR__ . '/test/Bootstrap.php',
);
