<?php
/**
 * Created by PhpStorm.
 * User: Oleksii Volkov
 * Date: 09.11.2015
 * Time: 18:39
 */

echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('OCTO') ?>
    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge') ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => '/img/octo-small-logo.png'))
        ->prependStylesheet('/css/login.css')
        ->prependStylesheet('/css/style.css')
        ->prependStylesheet('/css/bootstrap-theme.min.css')
        ->prependStylesheet('/css/bootstrap.min.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile('/js/bootstrap.min.js')
        ->prependFile('/js/jquery.min.js')
        ->prependFile('/js/login.js')
        ->prependFile('/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9'))
        ->prependFile('/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9')) ?>

</head>
<body>
<div class="container">
    <div class="row" id="pwd-container">
        <div class="col-md-4 col-md-offset-4">
            <section class="login-form">
                <form method="post" action="#" role="login" novalidate>
                    <img src="/img/text-logo.png" class="img-responsive" alt=""/>
                    <input type="email" name="email" placeholder="Email" required class="form-control input-lg"/>
                    <input type="password" class="form-control input-lg" id="password" placeholder="Password"/>

                    <div class="pwstrength_viewport_progress"></div>
                    <button type="submit" name="go" class="btn btn-lg btn-primary btn-block">Sign in</button>
                    <div>
                        <a href="#">Create account</a> or <a href="#">reset password</a>
                    </div>
                </form>
            </section>
        </div>
    </div>
    <div class="buffer"></div>
</div>
<!-- /container -->
<hr>
<footer>
    <div class="row">
        <div class="col-md-4 col-md-offset-4 text-center">
            <p>&copy; 2015 developed by Oleksii Volkov. All rights reserved.</p>
        </div>
    </div>
</footer>
</body>
</html>