<?php
/**
 * Created by PhpStorm.
 * User: Oleksii Volkov
 * Date: 09.11.2015
 * Time: 18:39
 */
?>

<link rel="stylesheet" href="/css/login.css"/>
<script src="/js/login.js"></script>

<div class="container">

    <div class="row" id="pwd-container">
        <div class="col-md-4"></div>

        <div class="col-md-4">
            <section class="login-form">
                <form method="post" action="#" role="login" novalidate>
                    <img src="/img/text-logo.png" class="img-responsive" alt=""/>
                    <input type="email" name="email" placeholder="Email" required class="form-control input-lg"/>
                    <input type="password" class="form-control input-lg" id="password" placeholder="Password"/>

                    <div class="pwstrength_viewport_progress"></div>
                    <button type="submit" name="go" class="btn btn-lg btn-primary btn-block">Sign in</button>
                    <div>
                        <a href="#">Create account</a> or <a href="#">reset password</a>
                    </div>
                </form>
            </section>
        </div>
    </div>
</div>